### ISSUE TITLE
Need Help with your Issue with Device Permission

### ISSUE THREAD

**Issue by 1mehmood0** [chenxizhang/teamsplatform#1]
[THIS ISSUE](https://github.com/MicrosoftDocs/msteams-docs/issues/3224#issue-875033240)

I want to know how you resolved that?
Can you please help me i am stuck here for a while.

**Comment by chenxizhang** [comment]
@1mehmood0 can you describe your issue a little bit in detail?

I remembered that I don't do any specific works on it, and the next time it works for me. Maybe a bug related to the mobile app client I think.
